# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170607_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['position'], 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='gallery',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
