# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 07:26
from __future__ import unicode_literals

import api.utils
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gallery_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['position'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galerie 123'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['position'], 'verbose_name': 'Gallery image', 'verbose_name_plural': 'Gallery images'},
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=api.utils.upload_directory_path, verbose_name='obraz'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='position',
            field=models.IntegerField(default=0, verbose_name='pozycja'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tytuł'),
        ),
    ]
